new_project -name leon3mp -folder . -createimpl_name precision
setup_design -manufacturer Xilinx -family SPARTAN-6 -part XC6SLX45csg324 -package csg324 -speed -3
set_input_dir .
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/stdlib/version.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/stdlib/config.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/stdlib/stdlib.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/sparc/sparc.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/modgen/multlib.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/modgen/leaves.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/amba.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/devices.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/defmst.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/apbctrl.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/ahbctrl.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/dma2ahb_pkg.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/dma2ahb.vhd
add_input_file -format VHDL -work grlib /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/grlib/amba/ahbmst.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/gencomp/gencomp.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/gencomp/netcomp.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/inferred/memory_inferred.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/inferred/ddr_inferred.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/inferred/mul_inferred.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/inferred/ddr_phy_inferred.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/inferred/ddrphy_datapath.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/dware/mul_dware.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/memory_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/buffer_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/pads_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/clkgen_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/tap_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/ddr_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/ddr_phy_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/grspwc_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/grspwc2_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/grusbhc_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/ssrctrl_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/sysmon_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/mul_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/spictrl_unisim.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/spictrl_unisim_comb0.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/unisim/spictrl_unisim_comb1.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/allclkgen.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/allddr.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/allmem.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/allmul.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/allpads.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/alltap.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/clkgen.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/clkmux.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/clkand.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/ddr_ireg.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/ddr_oreg.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/ddrphy.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram64.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram_2p.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram_dp.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncfifo.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/regfile_3p.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/tap.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/techbuf.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/nandtree.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/clkpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/clkpad_ds.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/inpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/inpad_ds.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/iodpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/iopad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/iopad_ds.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/lvds_combo.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/odpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/outpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/outpad_ds.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/toutpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/skew_outpad.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grspwc_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grspwc2_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grlfpw_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grfpw_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/leon4_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/mul_61x61.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/cpu_disas_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grusbhc_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/ringosc.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/ssrctrl_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grpci2_phy_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/system_monitor.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/grgates.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/inpad_ddr.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/outpad_ddr.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/iopad_ddr.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram128bw.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram256bw.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram128.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram156bw.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/techmult.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/spictrl_net.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/scanreg.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncrambw.vhd
add_input_file -format VHDL -work techmap /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/techmap/maps/syncram_2pbw.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/comp/ethcomp.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/greth_pkg.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/eth_rstgen.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/eth_edcl_ahb_mst.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/eth_ahb_mst.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/greth_tx.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/greth_rx.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/core/grethc.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/wrapper/greth_gen.vhd
add_input_file -format VHDL -work eth /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/eth/wrapper/greth_gbit_gen.vhd
add_input_file -format VHDL -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/occomp/occomp.vhd
add_input_file -format VHDL -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/i2c/i2c_master_bit_ctrl.vhd
add_input_file -format VHDL -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/i2c/i2c_master_byte_ctrl.vhd
add_input_file -format VHDL -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/i2c/i2coc.vhd
add_input_file -format VERILOG -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/spi/simple_spi_top.v
add_input_file -format VERILOG -work opencores /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/opencores/ac97/ac97_top.v
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/arith/arith.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/arith/mul32.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/arith/div32.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/memctrl/memctrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/memctrl/sdctrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/memctrl/sdctrl64.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/memctrl/sdmctrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/memctrl/srctrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/leon3.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmuconfig.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmuiface.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/libmmu.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/libiu.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/libcache.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/libproc3.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/cachemem.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmu_icache.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmu_dcache.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmu_acache.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmutlbcam.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmulrue.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmulru.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmutlb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmutw.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmu.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mmu_cache.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/cpu_disasx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/iu3.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/grfpwx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/mfpwx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/grlfpwx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/tbufmem.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/dsu3x.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/dsu3.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/proc3.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/leon3s.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/leon3cg.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/irqmp.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/grfpwxsh.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/grfpushwx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/leon3/leon3sh.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/misc.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/rstgen.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/gptimer.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbram.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbdpram.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbtrace.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbtrace_mb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbtrace_mmb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/grgpio.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbstat.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/logan.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/apbps2.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/charrom_package.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/charrom.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/apbvga.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/svgactrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/wild.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/wild2ahb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/grsysmon.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/gracectrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/grgpreg.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahbmst2.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/ahb_mst_iface.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/misc/grgprbank.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/net/net.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/uart.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/libdcom.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/apbuart.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/dcom.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/dcom_uart.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/uart/ahbuart.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/jtag.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/libjtagcom.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/jtagcom.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/ahbjtag.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/ahbjtag_bsd.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/bscanregs.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/jtag/bscanregsbd.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/ethernet_mac.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/greth.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/greth_mb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/greth_gbit.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/greth_gbit_mb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/greth/grethm.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddrphy_wrap.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddrsp16a.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddrsp32a.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddrsp64a.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddrspa.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddr2spa.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddr2buf.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddr2spax.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddr2spax_ahb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/ddr/ddr2spax_ddr.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2c.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2cmst.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2cmst_gen.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2cslv.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2c2ahbx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2c2ahb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/i2c/i2c2ahb_apb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spi.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spimctrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spictrlx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spictrl.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spi2ahbx.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spi2ahb.vhd
add_input_file -format VHDL -work gaisler /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/gaisler/spi/spi2ahb_apb.vhd
add_input_file -format VHDL -work esa /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/esa/memoryctrl/memoryctrl.vhd
add_input_file -format VHDL -work esa /chalmers/sw/unsup64/grlib-gpl-1.1.0-b4113/lib/esa/memoryctrl/mctrl.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/iodrp_controller.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/iodrp_mcb_controller.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/mcb_raw_wrapper.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/mcb_soft_calibration.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/mcb_soft_calibration_top.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/memc3_infrastructure.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/memc3_wrapper.vhd
add_input_file -format VHDL -work work mig37/mig_37/user_design/rtl/mig_37.vhd
add_input_file -format VHDL -work work config.vhd
add_input_file -format VHDL -work work ahbrom.vhd
add_input_file -format VHDL -work work ahb2mig_sp601.vhd
add_input_file -format VHDL -work work led_pkg.vhd
add_input_file -format VHDL -work work ledmod.vhd
add_input_file -format VHDL -work work adder_pkg.vhd
add_input_file -format VHDL -work work SKadder.vhd
add_input_file -format VHDL -work work leon3mp.vhd
setup_design -design leon3mp
setup_design -retiming
setup_design -vhdl
setup_design -transformations=false
setup_design -frequency="220"

save_impl
